# Generated by Django 4.0.5 on 2022-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_language',
            field=models.IntegerField(choices=[(0, 'Ua'), (1, 'Ru'), (2, 'En')], default=0),
        ),
    ]
