# Generated by Django 4.0.5 on 2022-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_user_bot_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bot_language',
            field=models.CharField(default='RU', max_length=2),
        ),
    ]
