# Generated by Django 4.0.5 on 2022-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_media_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
